CXX = g++
CXXFLAGS = -Wall -g -std=c++11 

CaffeineBeverage:
	$(CXX) $(CXXFLAGS) -o CaffeineBeverage.out  CaffeineBeverage.cc

CaffeineBeverageWithHook:
	$(CXX) $(CXXFLAGS) -o CaffeineBeverageWithHook.out  CaffeineBeverageWithHook.cc

clean:
	rm *.o