CXX = g++
CXXFLAGS = -Wall -g -std=c++11 

DuckTestDrive.out: 
	$(CXX) $(CXXFLAGS) -o DuckTestDrive.out  DuckTestDrive.cc

HomeTheaterTestDrive.out: 
	$(CXX) $(CXXFLAGS) -o HomeTheaterTestDrive.out  HomeTheaterTestDrive.cc

clean:
	rm *.o